#  Redis is used for in-memory data storage and allows users to access the data over API.
#    **Manual Installation of Redis.**
#    1. Install Redis.
#
#    ```bash
#
#    # curl -L https://raw.githubusercontent.com/roboshop-devops-project/redis/main/redis.repo -o /etc/yum.repos.d/redis.repo
#    # yum install redis -y
#    ```
#
#    2. Update the BindIP from `127.0.0.1` to `0.0.0.0` in config file `/etc/redis.conf` & `/etc/redis/redis.conf`
#
#    3. Start Redis Database
#
#    ```bash
#    # systemctl enable redis
#    # systemctl start redis
#    ```

- name: Setup YUM Repos
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: installed

- name: Update Redis config- listen IP address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis service
  ansible.builtin.systemd:
    name: redis
    state: started
    enabled: yes




