- name: Copy mongodb repos
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install Mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update Mongodb configuration - Update listen IP address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongodb service
  ansible.builtin.systemd:
    name: mongodb
    state: started
    enabled: yes