- name: Play level variables
  hosts: all
  vars:
    URL: ply.example.com
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL= {{URL}}


- name: play level varibles from files
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: print URL
      ansible.builtin.debug:
        msg: URL={{URL}}
