- name: demo on loops
  hosts: local host
  tasks:
    - name: print fruit name
      debug:
        msg: fruit name = {{item}}
      loop:
        - apple
        - mango
        - orange
    - name: print fruit name and inventory count
        debug:
          msg: fruit name = {{item.name}} , inventory count = {{item.count}}
          loop:
            - {name: apple, count: 10}
            - {name: mango, count: 20}
            - {name: orange, count: 30}

