- name: demo on loops
  hosts: localhost
  tasks:
    - name: Print Fruit Name
      debug:
        msg: Fruit Name = {{item}}
      loop:
        - apple
        - mango
        - orange

    - name: Print Fruit Name and Inventory Count
      debug:
        msg: Fruit Name = {{item.name}} , Available Count = {{item.count}}
      loop:
        - {name: apple, count: 10}
        - {name: mango, count: 20}
        - {name: orange, count: 30}

