- name: Demo on Conditions
  hosts: localhost
  vars:
    a: abc
    b: 10
    c: true
    d: false
  tasks:
    - name: condition on strings1
      ansible.builtin.debug:
        msg: strings contion is true
      when: a == "abc"
    - name: condition on strings2
      ansible.builtin.debug:
        msg: strings contion is not true
      when: a != "abc"
      ## strings should be in quotes in when condition
    - name: condition on numbers1
      ansible.builtin.debug:
        msg: numbers contion is true
      when: b == 10
    - name: condition on numbers2
      ansible.builtin.debug:
        msg: numbers contion is not true
      when: b == 5
    - name: condition on numbers3
      ansible.builtin.debug:
        msg: numbers contion is true
      when: b <= 20

    - name: boolean operations
      ansible.builtin.debug:
        msg: C is True
      when: c
    - name: boolean operations
      ansible.builtin.debug:
        msg: D is False
      when: d
